language: cpp
before_script:
 - mkdir /home/travis/build/luzbel/TestTravis/VigasocoSDL/input
 - mkdir /home/travis/build/luzbel/TestTravis/VigasocoSDL/video
 - mkdir /home/travis/build/luzbel/TestTravis/VigasocoSDL/audio
script: make
addons:
  apt:
    packages:
    - libsdl2-dev
