version: 1.0.{build}.TEST-EMSCRIPTEN
environment:
  matrix:
# Mientras pruebo Emscripten, desactivo los otros builds
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#      BUILD_CMD: "C:\\MinGW\\bin\\mingw32-make -f Makefile.MinGW"
#      ARTIFACT_FILE: "build\\win\\VigasocoSDL-Beta.Win32.$(APPVEYOR_REPO_TAG_NAME).zip"
#    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
#      BUILD_CMD: make -f Makefile
#      ARTIFACT_FILE: "build/linux/VigasocoSDL-Beta.Linux.$(APPVEYOR_REPO_TAG_NAME).zip"
#    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
#      BUILD_CMD: make -f Makefile.static
#      ARTIFACT_FILE: "build/linux/VigasocoSDL-Beta.Linux.static.$(APPVEYOR_REPO_TAG_NAME).zip"
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      BUILD_CMD: emmake -f Makefile.emscripten
      ARTIFACT_FILE: "build/linux/VigasocoSDL-Beta.Linux.static.$(APPVEYOR_REPO_TAG_NAME).zip"
branches:
  # whitelist
  only:
    - xbr
install:
- cmd: >-
    
    appveyor DownloadFile https://www.libsdl.org/release/SDL-devel-1.2.15-mingw32.tar.gz

    7z x SDL-devel-1.2.15-mingw32.tar.gz -so | 7z x -si -ttar -oc:\MinGW

    ren c:\MinGW\SDL-1.2.15 SDL-1.2.14

    mkdir %APPVEYOR_BUILD_FOLDER%\VigasocoSDL\input

    mkdir %APPVEYOR_BUILD_FOLDER%\VigasocoSDL\video

    mkdir %APPVEYOR_BUILD_FOLDER%\VigasocoSDL\audio
    
    mkdir %APPVEYOR_BUILD_FOLDER%\build\
    
    mkdir %APPVEYOR_BUILD_FOLDER%\build\win
- sh: >-
    # export ARTIFACT_FILE="build/linux/VigasocoSDL-Beta.Linux.zip"
    
    sudo apt-get update
    
    sudo apt-get install -y libsdl1.2-dev
    
    # estos directorios ahora los crea el Makefile    
    #    mkdir $APPVEYOR_BUILD_FOLDER/VigasocoSDL/input
    
    #    mkdir $APPVEYOR_BUILD_FOLDER/VigasocoSDL/video
    
    #    mkdir $APPVEYOR_BUILD_FOLDER/VigasocoSDL/audio
    
    # Esto debería crearlo el Makefile 
    
    mkdir $APPVEYOR_BUILD_FOLDER/build
    
    mkdir $APPVEYOR_BUILD_FOLDER/build/linux
    
    # Emscripten
    
    git clone https://github.com/emscripten-core/emsdk.git
    
    cd emsdk
    
    ./emsdk install latest
    
    ./emsdk activate latest
    
    source ./emsdk_env.sh
    
    cd $APPVEYOR_BUILD_FOLDER
build_script:
- cmd: >-
    set PATH=C:\MinGW\bin\;%PATH%

    %BUILD_CMD%

    cp c:\MinGW\bin\libgcc_s_dw2-1.dll VigasocoSDL

    cp c:\MinGW\bin\libstdc++-6.dll VigasocoSDL

    cp c:\MinGW\SDL-1.2.14\bin\SDL.dll VigasocoSDL

    7z a -tzip %ARTIFACT_FILE% VigasocoSDL\VigasocoSDL.exe VigasocoSDL\roms VigasocoSDL\input VigasocoSDL\video VigasocoSDL\audio VigasocoSDL\libgcc_s_dw2-1.dll VigasocoSDL\libstdc++-6.dll VigasocoSDL\SDL.dll
- sh: >-
    $BUILD_CMD
    
    zip $ARTIFACT_FILE VigasocoSDL/VigasocoSDL VigasocoSDL/audio/libVigasocoNULLAudioPlugin.so VigasocoSDL/audio/libVigasocoSDLAudioPlugin.so VigasocoSDL/video/libVigasocoSDLDrawPlugin.so VigasocoSDL/input/libVigasocoSDLInputPlugin.so VigasocoSDL/roms/abadia/*
    
    cp $ARTIFACT_FILE $APPVEYOR_BUILD_FOLDER
artifacts:
- path: build\*\*
  name: zips

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  provider: GitHub
  auth_token:
    secure: NjwXLrQA93QpoBvq4mq0S/rYEDz6QXToDH0IAkD4Ppwqj8Rj3Y3wM6myfVxqIQCv
  draft: false
  prerelease: true
  on:
    branch: appveyor
    APPVEYOR_REPO_TAG: true
