version: 1.0.{build}
install:
- cmd: >-
    appveyor DownloadFile https://www.libsdl.org/release/SDL-devel-1.2.15-mingw32.tar.gz

    7z x SDL-devel-1.2.15-mingw32.tar.gz -so | 7z x -si -ttar -oc:\MinGW

    ren c:\MinGW\SDL-1.2.15 SDL-1.2.14

    rem dir c:\MinGW\SDL-1.2.14

    rem dir c:\mingw\bin

    rem dir mkdir %APPVEYOR_BUILD_FOLDER%

    mkdir %APPVEYOR_BUILD_FOLDER%\VigasocoSDL\input

    mkdir %APPVEYOR_BUILD_FOLDER%\VigasocoSDL\video

    mkdir %APPVEYOR_BUILD_FOLDER%\VigasocoSDL\audio
build_script:
- cmd: >-
    set PATH=C:\MinGW\bin\;%PATH%

    C:\MinGW\bin\mingw32-make -f Makefile.MinGW

    cp c:\MinGW\bin\libgcc_s_dw2-1.dll VigasocoSDL

    cp c:\MinGW\bin\libstdc++-6.dll VigasocoSDL

    cp c:\MinGW\SDL-1.2.14\bin\SDL.dll VigasocoSDL

    7z a -tzip VigasocoSDL.zip VigasocoSDL\VigasocoSDL.exe VigasocoSDL\roms VigasocoSDL\input VigasocoSDL\video VigasocoSDL\audio VigasocoSDL\libgcc_s_dw2-1.dll VigasocoSDL\libstdc++-6.dll VigasocoSDL\SDL.dll
artifacts:
- path: VigasocoSDL.zip
